import { Brand } from "@/types/brand";

const brandData: Brand[] = [
  
  {
    id: 0.2,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-13.png",
    imageLight: "/images/brand/brand-dark-13.png",
  },
  {
    id: 0.3,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-10.png",
    imageLight: "/images/brand/brand-dark-10.png",
  },
  {
    id: 0.4,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-01.svg",
    imageLight: "/images/brand/brand-dark-01.svg",
  },
  {
    id: 0.5,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-02.svg",
    imageLight: "/images/brand/brand-dark-02.svg",
  },
  {
    id: 0.6,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-15.svg",
    imageLight: "/images/brand/brand-dark-15.svg",
  },
  {
    id: 0.7,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-07.png",
    imageLight: "/images/brand/brand-dark-07.png",
  },
  {
    id: 0.8,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-16.png",
    imageLight: "/images/brand/brand-dark-16.png",
  }, 
  {
    id: 0.11,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-17.png",
    imageLight: "/images/brand/brand-dark-17.png",
  }, 
  {
    id: 0.12,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-12.jpeg",
    imageLight: "/images/brand/brand-dark-12.jpeg",
  }, 
  {
    id: 0.13,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-light-11.png",
    imageLight: "/images/brand/brand-dark-11.png",
  }, 
  {
    id: 0.14,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-18.png",
    imageLight: "/images/brand/brand-dark-18.png",
  }, 
  {
    id: 0.15,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-03.svg",
    imageLight: "/images/brand/brand-dark-03.svg",
  },
  {
    id: 0.15,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-05.svg",
    imageLight: "/images/brand/brand-dark-05.svg",
  },
  {
    id: 0.16,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-14.png",
    imageLight: "/images/brand/brand-dark-14.png",
  }, 
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-19.png",
    imageLight: "/images/brand/brand-dark-19.png",
  },
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-20.png",
    imageLight: "/images/brand/brand-20.png",
  },
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-08.png",
    imageLight: "/images/brand/brand-dark-08.png",
  },
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-21.png",
    imageLight: "/images/brand/brand-21.png",
  },
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-22.png",
    imageLight: "/images/brand/brand-22.png",
  },
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-23.png",
    imageLight: "/images/brand/brand-23.png",
  },
  {
    id: 0.17,
    name: "Client",
    href: "#",
    image: "/images/brand/brand-dark-06.svg",
    imageLight: "/images/brand/brand-dark-06.svg",
  }
];

export default brandData;
